"""
This module contains the configuration for the asset analyst system.
"""

from enum import Enum
from typing import Any


class ConfigEnum(Enum):
    GOOGLE_API_KEY = "GOOGLE_API_KEY"
    LANGCHAIN_TRACING_V2 = "LANGCHAIN_TRACING_V2"
    LANGCHAIN_PROJECT = "LANGCHAIN_PROJECT"
    LANGCHAIN_ENDPOINT = "LANGCHAIN_ENDPOINT"
    TAVILY_API_KEY = "TAVILY_API_KEY"
    GOOGLE_MODEL = "GOOGLE_MODEL"
    MODEL_TEMPERATURE = "MODEL_TEMPERATURE"
    TAVILY_SEARCH_COUNT = "TAVILY_SEARCH_COUNT"
    OPENAI_API_KEY = "OPENAI_API_KEY"
    OPENAI_MODEL_NAME = "OPENAI_MODEL_NAME"
    DEFAULT_MODEL = "DEFAULT_MODEL"
    ANTHROPIC_MODEL_NAME = "ANTHROPIC_MODEL_NAME"
    ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"
    GROQ_MODEL_NAME = "GROQ_MODEL_NAME"
    GROQ_API_KEY = "GROQ_API_KEY"

    def __str__(self):
        return self.value
